### ISSUE TITLE
Open existing MLFlow UI when `https://` scheme is provided as `mlflow_tracking_uri`

### ISSUE THREAD

**Issue by mariusz89016** [Galileo-Galilei/kedro-mlflow#275]
## Description
`kedro-mlflow` allows to specify tracking server in config using `mlflow_tracking_uri` property. Also, the same property is passed to `--backend-store-uri` when running `kedro mlflow ui`. It would be nice to have similar experience (as with supported by MLFlow schemes) with `https://` URIs.

## Context
I was thinking about general user experience and that UI-related command caught my attention.
Potential use case: a company can generate Kedro projects based on a template which has defined MLFlow external tracking server. Users want to access MLFlow UI (hopefully) just by using `kedro mlflow ui` because it's easier for them.
 
## Possible Implementation
(If you consider this feature good future direction for the plugin) a potential implementation could look like this:
* check whether URI starts with `https://` and redirect user to that address
* (optional) 2 distinct properties for tracking server and backend store - you can use sensible defaults and/or fallbacks if not specified

## Possible Alternatives
Maybe user-friendly info would be enough?

Thanks!

**Comment by Galileo-Galilei** [comment]
Hi @mariusz89016, thank you for the feedback. I am not sure sure to understand what you want so do not hesitate to tell me if I misunderstood. 

> check whether URI starts with https:// and redirect user to that address

You already have a remote tracking server properly set up, and you do not want to launch a ui server, but rather just to open the uri in your browser right? Something like ``webbrowser.open`` instead of running ``mlflow ui`` command?

> (optional) 2 distinct properties for tracking server and backend store - you can use sensible defaults and/or fallbacks if not specified

I am not sure I understand. If the tracking server is set up (e.g. you launch [this command](https://www.mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers)), your ``ui`` only redirect to the tracking uri of this server, you do not need to specify artifact storage. The only artifact root you can specify is eventually a local path if you want to store artifacts in another folder than the default ``./mlruns``, but you cannot specify a *remote* artifact storage to the ``ui`` command as [described in the documentation](https://mlflow.org/docs/latest/cli.html#mlflow-ui).

**Comment by Galileo-Galilei** [comment]
Closed by #284
