### ISSUE TITLE
Auto-pickle parameters on modelify calls

### ISSUE THREAD

**Issue by Mercurrent** [Galileo-Galilei/kedro-mlflow#282]
## Description

When you run 'modelify' command for some pipeline relying on parameters you get " Dataset 'parameters' is not persisted currently." error. The issue seems similar to #158

**Comment by Galileo-Galilei** [comment]
Hello @Mercurrent, 

thank you for the bug report. You are right that it is the same error, and I will fix it soon (within weeks). The current workarounds are: 
- use ``pipeline_ml_factory`` to automatically save your model after training. this is the recommended way to save kedro pipelines as model in ``kedro-mlflow``. I'd be glad to help if needed.
- If you really want  to use the ``modelify`` command, write your parameter in a yaml file, and call it from the ``catalog.yml`` instead of ``parameters.yml``, e.g.: 

Current: 

```yaml
# parameters.yml*
my_param: 1
```  

```python
# pipeline.py
def create_pipeline(**kwargs):
    Pipeline([
        node(func=your_func, inputs="params:my_param", outputs="final_data")
    ])
```

Workaround: 


```yaml
# catalog.yml
my_param:
    type: yaml.YAMLDataSet
    filepath: /path/to/my_param.yml
``` 

```yaml
# /path/to/my_param.yml
1 # no prefix, it is a dataset
```

```python
# pipeline.py
def create_pipeline(**kwargs):
    Pipeline([
        node(func=your_func, inputs="my_param", outputs="final_data") # remove "params:"
    ])
```
