### ISSUE TITLE
Use mlflow-skinny instead of mlflow as default requirement

### ISSUE THREAD

**Issue by marrrcin** [Galileo-Galilei/kedro-mlflow#344]
## Description
There is a `mlflow-skinny` package which contains all of the tracking features with minimal set of dependencies. Have you considered using it in `kedro-mlflow`? Regardless of the answer I would like to know your thoughts on that matter. Thanks!

## Context
Adding full `mlflow` package to docker images is sometimes an overkill, since mlflow server's components are not required to run training jobs and track metrics / artifacts, and those additional dependencies contribute to larger docker images.

## Possible Implementation
Have mlflow-skinny as default and full mlflow as an optional requirement.

## Possible Alternatives
Leave the package as is.

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, this is a wonderful idea. I think I tried it a long time ago but I remembered I had some issues with the ``MlflowClient``. I can envision a change in requirements, but I have  to check a bunch of things first: 
- [ ] Check how many tests are failing when replacing ``mlflow`` by ``mlflow-skinny``
- [ ] Assess what changes are necessary and their impacts (especially the ``MlflowClient`` and the ``import`` statement)
- [ ] If we decide to offer by default only a subset of mlflow functionalities, make clear and easy how to have the full set of requirements (maybe an extra requirements?)

I add it to the roadmap and I'll keep you informed. If you want to make some tests on your own to speed up development, I'd be happy to provide guidance if needed.

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, I've been playing a little with mlflow-skinny, and unfortunately I will not implement this suggestion. With mlflow-skinny, all features related to models (pipeline_ml_factory, kedro mlflow modelify, but also to model loading especially wirth the registry are no logner available. Since the ``MlflowHook`` imports everything, ti would be a big refactoring to separate all functionalities, especially given that if I had different hooks they would still need to interoperate altogether (to get the current configuration information). 

This is too big a change and I can't afford this for maintenance reason. If you need to have "only" the tracking capabilities, feel free to duplicate the hook on your own and remove anything you do not want to. 

My apologies for not finding a more convenient solution here.

**Comment by marrrcin** [comment]
Sure, no problem! Thanks for the update and your research 🙂
