### ISSUE TITLE
Support for MLflow 2.0

### ISSUE THREAD

**Issue by mb1069** [Galileo-Galilei/kedro-mlflow#390]
Hi, 
Is kedro_mlflow going to have support for MLflow 2.0 and above in the near future?

Thank you for an awesome package!

**Comment by Galileo-Galilei** [comment]
Hi, I obviously do plan to support ``mlflow>=2.0``, but I haven't decided yet what the best solution is:
- in an **ideal world, I'd love to support ``mlflow~1.X`` AND ``mlflow ~2.X``**. This requires monkey patching a bunch of mlflow functions (especially the ``MlflowClient``) and this is both a lot of work to setup and generates a lot of maintenance burden (lots of tests are breaking, I need a CI to test both scenario, I need to monkey patch all test.s, there is always some very weird side effects which can happen. by modifiying the inner working of mlflow..). **Unfortunately, this scenario is very unlikely** unless I have some help to maintain this package. Feel free to volunteer 😄 
- The most realistic scenario is that I will drop ``mlflow~1.X`` series at some point and start to support mlflow 2.0. My problem here is that I *think* that most people have not migrated to ``mlflow~2.X`` yet (I can't verify it from user research, but if people come and upvote your question I will reconsider this). 

➡️ The current scenario I have in mind is to move to mlflow 2 **after** moving to ``kedro ==0.19``. My intuition is that it could be done in rougly 1 year, say early 2024. 

If many people complain  about it, I may create a branch to enable installing a development version of kedro_mlflow from github instead of PyPI which would be compatible with mlflow 2. 

Have you already migrated to mlflow 2 in your org?

**Comment by Galileo-Galilei** [comment]
Hi @mb1069 , @edhenry, @melaanya, 

can you give it a try to by installing this PR: ``pip install git+https://github.com/Galileo-Galilei/kedro-mlflow.git@mlflow2``? I think I will be able to support both mlflow 1 & 2 and I can release it very soon but I'd like to add your feeback first.

**Comment by mb1069** [comment]
Hi @Galileo-Galilei , I've run your PR locally and it hasn't broken our workflow / deployment! Looking forward to the release.
