### ISSUE TITLE
Show loaded model version in logs

### ISSUE THREAD

**Issue by mck-star-yar** [Galileo-Galilei/kedro-mlflow#552]
## Description

When I'm using `MlflowModelRegistryDataset` with the load parameter set to `latest` logs don't capture the exact version loaded from mlflow. It'd be good to propagate them.

## Context

As a DS, looking at the logs I'd like to know what version of model was loaded

## Possible Implementation

Ideally, that should live on the mlflow side. But as long as that's not the case we can manually check if user passed the `latest` arg and log latest version available for the model.

**Comment by Galileo-Galilei** [comment]
Hi, eventually I could store a bunch of metadata but I also think this should live on mlflow's side. I am a bit reluctant to log too many custom things. I think I can log some metadata of the loaded, but I don't know if I should only log it in hte logs, or in mlflow itself (because one may want to load a model without logging the inference run in mlflow, especially in production). Could yu elaborate more on your ideal result?

**Comment by mck-star-yar** [comment]
> Could yu elaborate more on your ideal result?

Ideal result would be just to show loaded model version, something like: `Loaded model version v10`

**Comment by Galileo-Galilei** [comment]
It turns out, it is pretty hard in general to map a model to its associated version for many reasons : 
- a model does not know about the associated model registry metadata, because the same model (in the run id sense) can be assigned to several model name in the registry, and can have differents sages  versions
-  with the deprecation of stages and introduction of aliases, it's hard to assess what info is relevant for display, and it's hard to make it in a retrocmpatible way
- recreating all mlflow logic to fetch the version is possible, 'mostly with ``get_latest_versions("demo_model", stages=["None"])``), but it generates a lot of boilerplate code on my side, and possible performance issues and maintenance bruden. 

**Decision:** I won't retrieve the version, but I'll log the run id of the exat model which has been loaded, helping to further debugging. I might reconsider this in the future when stages are entirely removed and not just deprectaed, and the mlfow API gets simpler.

**Comment by mck-star-yar** [comment]
Great resolution given mlflow's limitations 👏 
logging `run_id` will simplify debugging a lot
