### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by t00rgore** [Galileo-Galilei/kedro-mlflow#6]
A catch-all ticket to gather documentation improvement ideas.

1. Mark code blocks in README.md's Markdown with specific language - you can use 
```
```python
``` 
or
```
```yml
```
at the beginning of a code block to enable syntax highlighting.

**Comment by Galileo-Galilei** [comment]
Hello @kaemo, this is the next task I will be working on. I have in mind the following items (in addition to your remark): 
- [ ] Add community files to enforce collaboration (I will likely stick to github defaults here): 
    - [ ] Code of conduct
    - [ ] Contributing guidelines
    - [ ] Issue templates
    - [ ] Pull request template
- [ ] Define a detailed overview of the documentation structure.
- [ ] Correct the README which is obsolete since ``kedro`` release ``0.16``.

**Comment by Galileo-Galilei** [comment]
Update the readme:
- [ ] Add a section to warn for the beta status of the plugin (and specify we use SemVer)
- [ ] Add a section with comptibiltiy between mlflow, kedro and kedro mlflow different versions
- [ ] Move "main contributors" section to the end of the README with the contributing section

**Comment by Galileo-Galilei** [comment]
It is very common to have some broken links in the documentation. I suggest we add a CI step to check for broken links.
